# neural networks using gaussian initiation
echo 'Now running neural nets: sigmoid activation, 2 hidden layers'
echo 'Nodes=5, T=100, gaussian init, learn_rate=0.1, d=0.1'
python3 driver.py ./bank-note/train.csv ./bank-note/test.csv 5 100 'gaussian'
echo 'Now running neural nets: sigmoid activation, 2 hidden layers'
echo 'Nodes=10, T=100, gaussian init, learn_rate=0.1, d=0.1'
python3 driver.py ./bank-note/train.csv ./bank-note/test.csv 10 100 'gaussian'
echo 'Now running neural nets: sigmoid activation, 2 hidden layers'
echo 'Nodes=25, T=100, gaussian init, learn_rate=0.1, d=0.1'
python3 driver.py ./bank-note/train.csv ./bank-note/test.csv 25 100 'gaussian'
echo 'Now running neural nets: sigmoid activation, 2 hidden layers'
echo 'Nodes=50, T=100, gaussian init, learn_rate=0.1, d=0.1'
python3 driver.py ./bank-note/train.csv ./bank-note/test.csv 50 100 'gaussian'
echo 'Now running neural nets: sigmoid activation, 2 hidden layers'
echo 'Nodes=100, T=100, gaussian init, learn_rate=0.01, d=0.03'
python3 driver.py ./bank-note/train.csv ./bank-note/test.csv 100 100 'gaussian' 0.01 0.03

# neural networks using zeros initiation
echo 'Now running neural nets: sigmoid activation, 2 hidden layers'
echo 'Nodes=5, T=100, zeros init, learn_rate=0.1, d=0.1'
python3 driver.py ./bank-note/train.csv ./bank-note/test.csv 5 100 'zeros'
echo 'Now running neural nets: sigmoid activation, 2 hidden layers'
echo 'Nodes=10, T=100, gaussian init, learn_rate=0.1, d=0.1'
python3 driver.py ./bank-note/train.csv ./bank-note/test.csv 10 100 'zeros'
echo 'Now running neural nets: sigmoid activation, 2 hidden layers'
echo 'Nodes=25, T=100, gaussian init, learn_rate=0.1, d=0.1'
python3 driver.py ./bank-note/train.csv ./bank-note/test.csv 25 100 'zeros'
echo 'Now running neural nets: sigmoid activation, 2 hidden layers'
echo 'Nodes=50, T=100, gaussian init, learn_rate=0.1, d=0.1'
python3 driver.py ./bank-note/train.csv ./bank-note/test.csv 50 100 'zeros'
echo 'Now running neural nets: sigmoid activation, 2 hidden layers'
echo 'Nodes=100, T=100, gaussian init, learn_rate=0.1, d=0.1'
python3 driver.py ./bank-note/train.csv ./bank-note/test.csv 100 100 'zeros'
